#!/usr/bin/env node
// Builds the country-flag sprite used by the phone field.
//
// WHY A RASTER SPRITE AND NOT SVG
//
// The obvious move is inline SVG flags. Measured, the full set is 2.58 MB:
// most flags are 200 bytes, but Mexico's coat of arms is 140 KB on its own and
// Turkmenistan's carpet guls are 42 KB. At the 20x15px this field displays,
// none of that detail is visible — it is 2.5 MB of eagle nobody can see.
//
// So: rasterise each flag once at 2x display size and stack them into a single
// vertical sprite. One request, ~100 KB for 246 flags, positioned by
// background-position. The ornate ones cost the same as the plain ones.
//
// Flags come from flagcdn.com (public domain, derived from Wikipedia's SVGs).
// Fetched at build time and self-hosted: the CSP forbids third-party images,
// and a form field that depends on someone else's CDN staying up is a form
// field that breaks.
//
// Run by hand (`npm run flags`), output committed. Never part of `npm run build`.

import sharp from "sharp";
import { writeFileSync } from "node:fs";
import countries from "../src/_data/countries.js";

const CELL_W = 40; // 2x the 20px display width
const CELL_H = 30;
const OUT = "src/assets/img/flags.webp";
const MANIFEST = "src/_data/flags.js";

// A few ISO codes have no flag on flagcdn (uninhabited territories, mostly).
// They fall back to a blank cell rather than failing the build — a missing
// flag beside a valid dial code is a cosmetic gap, not an error.
const blank = await sharp({
  create: { width: CELL_W, height: CELL_H, channels: 4, background: { r: 223, g: 231, b: 217, alpha: 1 } },
})
  .png()
  .toBuffer();

const list = countries.list;
const cells = [];
let missing = [];

for (const [i, c] of list.entries()) {
  const code = c.code.toLowerCase();
  let buf = blank;
  try {
    const res = await fetch(`https://flagcdn.com/${code}.svg`);
    if (res.ok) {
      const svg = Buffer.from(await res.arrayBuffer());
      // `fit: fill` deliberately: flags have wildly different aspect ratios
      // (Switzerland and Nepal are not 4:3) and letterboxing 246 of them would
      // read as a rendering bug. A uniform cell is the convention every
      // phone-input library uses.
      buf = await sharp(svg, { density: 200 })
        .resize(CELL_W, CELL_H, { fit: "fill" })
        .png()
        .toBuffer();
    } else {
      missing.push(c.code);
    }
  } catch {
    missing.push(c.code);
  }
  cells.push({ input: buf, left: 0, top: i * CELL_H });
  if (i % 40 === 0) process.stdout.write(".");
}
process.stdout.write("\n");

const sprite = await sharp({
  create: {
    width: CELL_W,
    height: CELL_H * list.length,
    channels: 4,
    background: { r: 0, g: 0, b: 0, alpha: 0 },
  },
})
  .composite(cells)
  // Lossless: flags are flat colour with hard edges, which lossy WebP smears
  // into visible fringing at this size. Lossless is also SMALLER here for the
  // same reason — large areas of identical pixels compress almost perfectly.
  .webp({ lossless: true, effort: 6 })
  .toBuffer();

writeFileSync(OUT, sprite);

// index maps ISO code -> row, so the CSS can compute background-position and
// the template never has to know the sprite's internal order.
const index = Object.fromEntries(list.map((c, i) => [c.code, i]));
writeFileSync(
  MANIFEST,
  `// GENERATED by scripts/make-flags.js — do not edit by hand.
// ISO 3166-1 alpha-2 -> row index in /img/flags.webp.
// Cell is ${CELL_W}x${CELL_H} at 2x, displayed at ${CELL_W / 2}x${CELL_H / 2}.
export default {
  cellWidth: ${CELL_W / 2},
  cellHeight: ${CELL_H / 2},
  rows: ${list.length},
  index: ${JSON.stringify(index)},
};
`,
);

console.log(`flags.webp  ${CELL_W}x${CELL_H * list.length}  ${(sprite.length / 1024).toFixed(0)}kB  ${list.length} flags`);
if (missing.length) console.log(`no flag available for: ${missing.join(", ")}`);
