#!/usr/bin/env node
// Fetches the FILLED marks: partnership trophies and social brand logos.
//
// These are separate from src/_data/icons.js, which holds the stroked engraved
// marks. Two modes on purpose: a stroked symbol reads as line work cut at the
// same weight as the guilloche, while a trophy or a brand logo is an OBJECT and
// has to be solid to be recognisable. A stroked X logo is not the X logo.
//
// Sources, both self-hosted because the CSP forbids third-party assets:
//   - Material Symbols Outlined (Apache 2.0), via fonts.gstatic.com
//   - Brand marks via Iconify (MDI, Apache 2.0; simple-icons, CC0)
//
// Material Symbols ship on a 0 -960 960 960 viewBox, not 0 0 24 24. They are
// normalised here rather than in the template, so every consumer sees one grid.
//
// Run by hand (`npm run marks`), output committed.

import { writeFileSync } from "node:fs";

const MATERIAL = {
  // Partnership tiers, in descending prestige. Picked from the trophy family
  // so the five read as one set rather than five unrelated glyphs.
  trophy_cup: "trophy",
  trophy_laurel: "workspace_premium",
  trophy_medal: "military_tech",
  trophy_star: "award_star",
  trophy_plain: "star",
};

const out = {};

// --- Material -------------------------------------------------------------
for (const [key, name] of Object.entries(MATERIAL)) {
  const url = `https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/${name}/default/24px.svg`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${name}: HTTP ${res.status}`);
  const svg = await res.text();
  const d = (svg.match(/<path[^>]*\sd="([^"]+)"/) || [])[1];
  if (!d) throw new Error(`${name}: no path found`);
  out[key] = { d, viewBox: "0 -960 960 960", source: `material:${name}` };
  console.log(`${key.padEnd(16)} material:${name}`);
}

// --- Brands ---------------------------------------------------------------
// Iconify's MDI set (Apache 2.0), not simple-icons: simple-icons removed
// LinkedIn over trademark policy, so a mixed-source set is the only way to get
// all three from a real library rather than hand-drawing one and having it sit
// visibly wrong beside two accurate ones.
const BRAND_SOURCES = {
  brand_linkedin: "mdi/linkedin",
  brand_facebook: "mdi/facebook",
  brand_x: "simple-icons/x",
};

for (const [key, path] of Object.entries(BRAND_SOURCES)) {
  const res = await fetch(`https://api.iconify.design/${path}.svg`);
  if (!res.ok) throw new Error(`${path}: HTTP ${res.status}`);
  const svg = await res.text();
  const d = (svg.match(/<path[^>]*\sd="([^"]+)"/) || [])[1];
  if (!d) throw new Error(`${path}: no path found`);
  out[key] = { d, viewBox: "0 0 24 24", source: `iconify:${path}` };
  console.log(`${key.padEnd(16)} iconify:${path}`);
}

const banner = `// GENERATED by scripts/make-marks.js — do not edit by hand.
//
// FILLED marks: partnership trophies and social brand logos. The stroked
// engraved marks live in icons.js; these are solid because a trophy and a
// brand logo are objects, not symbols, and a stroked X logo is not the X logo.
//
// Material Symbols and MDI are Apache 2.0, simple-icons CC0. All self-hosted.
// Material's native viewBox is 0 -960 960 960; it is preserved per-mark rather
// than rescaled, so the paths stay byte-identical to the source.
`;

writeFileSync(
  "src/_data/marks.js",
  `${banner}export default ${JSON.stringify(out, null, 2)};\n`,
);
console.log(`\n${Object.keys(out).length} marks written to src/_data/marks.js`);
